version: '3.13'

services:
  credit_scoring_api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://your-mlflow-server:5000  # if you use a remote MLflow server
    volumes:
      - ./mlruns:/app/mlruns
